apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rollouts-demo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  ignoreDifferences:
  - group: networking.istio.io
    kind: VirtualService
    jsonPointers:
    - /spec/http/0
  project: dev
  source:
    path: examples/istio
    repoURL: https://github.com/fgauna12/rollouts-demo.git
    targetRevision: HEAD
    kustomize:
      images:
        - 'argoproj/rollouts-demo=argoproj/rollouts-demo:bad-red'
  destination:
    namespace: "rollouts-demo"
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
    - ApplyOutOfSyncOnly=true #For Istio
    automated:
      selfHeal: true
      prune: true
