apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-socks-shop
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: previews
  source:
    path: k8s
    repoURL: https://github.com/fgauna12/socks-shop-k8s.git
    targetRevision: HEAD
    kustomize:
      images:
        - 'weaveworksdemos/front-end=$FULLY_QUALIFIED_IMAGE'
  destination:
    namespace: "dev-socks-shop"
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true